import Providers from "@/Redux/Provider";
import "./globals.css";
import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";

const oswald = Oswald({
  weight: ["300", "700"],
  variable: "--font-oswald",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Shop by BATOOL",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children?: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Providers>
          <Navbar></Navbar>
          {props.children}

        </Providers>
      </body>
    </html>
  );
}
